### PR TITLE
Blog post on how to parallelize your code

### PR DESCRIPTION
**Pull request by mmore500**

### CODE REVIEW

**Comment by mmore500** [comment]
Excited to read this when you put it together! RE code examples tackling a complex problem, be careful to choose the problem so that its complexity is illustrative towards specific points you’d like to make about parallelization. If there’s too much “real world” complexity that’s not directly tied to the parallelism points you’re trying to make, it might make life unnecessarily hard in the reader.

When selecting code snippets... if you’re showing “real” (production) code you could even consider stripping out lines that aren’t directly relevant. You might also consider just throwing together some minimal examples to show the ideas you’re interested in (e.g., class Foo with method bar... but hopefully with some more descriptive/interesting names)

**Comment by mmore500** [comment]
[Safari - Apr 23, 2020 at 00:26.pdf](https://github.com/mmore500/cse-491/files/4520296/Safari.-.Apr.23.2020.at.00.26.pdf)

**Comment by striebelhan** [comment]
Great blog post! I like the flowchart - it made it really easy to understand what you were doing to parallelize. You also had a lot of great info - I thought it was super interesting that it's more efficient to follow all branches down an if statement and determine the correct path at the end than it is to stop and evaluate the if each time. I never would've guessed!

**Comment by little11** [comment]
This is a really nice post. I especially liked the way you broke down a sort of approach to recognizing sections of code worth parallelizing. I think adding section headers would help keep the post organized and make it easier to go back and refer to parts of it. Also there's a lot of info in the diagrams and it was easy to get a little lost here and there. It might be helpful to highlight the parts that changed in each revised version of the diagram.

**Comment by bradleybauer** [comment]
Hey, I liked your post and I thought your example was interesting. It was nice to think about how data moves between serial and parallel in your example. Consider sharing your code on GitHub. Some people, after reading your post, may be interested in seeing a working example.

**Comment by kennedysean** [comment]
Great post! I especially liked the part about considering overhead and what to look for in code before parallelizing. I think it would be helpful if you added links to some of the parallel programming resources you mentioned in your post.

**Pull request merged**
