### PR TITLE
hannahs-blog-post

### PR DESCRIPTION
**Pull request by striebelhan**
I've done a little research on C++ modules, and I'm interested to learn more. For my blog post, I figured I could explain what modules are and how they differ from what C++ currently does, as well as potentially discuss the impact they will have on the language and beyond.

### CODE REVIEW

**Comment by mmore500** [comment]
Great! Looking forward to learning more about modules, as they're one of the 20 features I'm less familiar with.

As you poke around researching modules, I'd keep an eye out for a specific detail, example, or use case etc. if any catch your eye. Writing a broad overview/survey style blog post would be valuable (and I would love to read one!), but might become overwhelming... so if need be you could pivot to focusing in on a smaller point (& maybe situating it in terms of the bigger ideas).

**Comment by mmore500** [comment]
Looking good! There’s a lot of material in the outline, parts of which could on their own be full-fledged blog posts. The subsection you’re planning on for the main focus (“compare old c++ organization/compilation model with module organization/compilation model”) seems like it could be really compellingly organized around an “old way” example versus a “new way” example. You could design the examples so they’re minimal “slide-ware” code that have just what’s necessary to illustrate the points you want to highlight about the differences between the old way and the new way.

**Comment by mmore500** [comment]
[Safari - Apr 22, 2020 at 23:56.pdf](https://github.com/mmore500/cse-491/files/4520175/Safari.-.Apr.22.2020.at.23.56.pdf)

**Comment by little11** [comment]
It's really clearly written and easy to understand, which is great. The only thing I was confused about is this one sentence toward the end: "Then, in the compilation step, the module implementation **units** and precompiled module interface **unit** are compiled into object files to form the module." Do the interface units precompile all into one file, whereas implementation units go into multiple files? Or maybe it's a typo? Or maybe it's just something obvious I'm missing. Other than that my only comment is it might be better to include your code examples as typed code blocks instead of screenshots so readers can copy and paste your code.

**Comment by bradleybauer** [comment]
Hey, I thought your post was great. It was nice to see that modules maintain the familiar interface/implementation organization of code and how using modules can improve compilation performance. It would have been nice to see how to compile code that uses modules.

**Comment by kennedysean** [comment]
This post does a great job of explaining and comparing the current compilation model and the module-based compilation model. The pros and cons sections were especially helpful, since it helps understand why modules are being added and how they will help developers. I think links to additional resources such as some of the CppCon talks about modules would be nice to include.

**Comment by striebelhan** [comment]
2 sentence "clickbait":

According to C++ Standards committee member, Bryce Adelstein, "modules will have a greater impact than any other C++ feature since standardization." Let's break that down a bit by taking a look at how modules change C++ organization and compilation.

**Comment by mmore500** [comment]
Thanks for the blurb! merging

**Pull request merged**
