### PR TITLE
Create 2020-03-08-c++-macros.md

### PR DESCRIPTION
**Pull request by mmore500**
A general overview of macros in C++ with a few examples, and a discussion of why it's recommended not to use them.

### CODE REVIEW

**Comment by mmore500** [comment]
Topic looks good! It might also be really neat (but not necessary!) to have examples of why not to use macros (e.g., ugly/subtle bug examples) and some commentary on alternate approaches to using macros. I would also recommend keeping an eye open for smaller interesting tidbits along the way so if you end up needing to reduce the scope of the blog post you have a plan of where to focus in on.

**Comment by mmore500** [comment]
Looking good! And thanks for linking the sources you’re planning on checking out... I think any one of the three main sections you laid out could be a quality blog post on its own, If you end up focusing down to one or two of these, that would be fine! In your intro or conclusion there might be something interesting to be said about the long history of macros [via the c preprocessor](https://softwareengineering.stackexchange.com/questions/309389/what-is-the-origin-of-the-c-preprocessor) (& how they’re a kind of weird glommed on tool originally separate from the language that became permanently attached ) but that could also be an entire blog post its own too!

**Comment by mmore500** [comment]
[Safari - Apr 22, 2020 at 23:06.pdf](https://github.com/mmore500/cse-491/files/4520064/Safari.-.Apr.22.2020.at.23.06.pdf)

**Comment by striebelhan** [comment]
Great blog post! It's well written and organized, and I learned a lot. The section explaining what macros are is very clear, and the examples do a great job of illustrating your point. The examples in the "Why Not to Use Them" section were a little harder to follow. It might help to break them up and explain them in a little more detail?

**Comment by kennedysean** [comment]
I've never taken the time to really understand macros but this post made it really easy. I will definitely check out some of the resources that you hyperlinked.

**Pull request merged**
