### PR TITLE
Create 2020-03-05-data-oriented-design.md

### PR DESCRIPTION
**Pull request by kennedysean**
I want to do an analysis of data-oriented design practices and their relationship with object-oriented programming. This can include studying the trade-offs of data-oriented design, benchmarking with different examples, and considering how a data-oriented approach affects code productivity and maintainability.

### CODE REVIEW

**Comment by mmore500** [comment]
Looks like a good topic! It seems like people are doing impressive things with data oriented design (like this [nifty browser engine demo](https://youtu.be/yy8jQgmhbAU?t=210) from cppcon 2018) & it will be great to learn more about. 

I'd recommend keeping an eye out for a specific detail, example, or use case etc. if any grab your attention. Writing a broad overview/survey style blog post would be valuable (or even just one clearly defining and demonstrating the idea of data oriented design) but might become overwhelming... so if need be you could strip back to a smaller point (while situating in terms of bigger ideas).

**Comment by mmore500** [comment]
RE the outline, I think your planned commentary on how questions of data vs object oriented design apply to larger software projects will definitely be valuable. When selecting code snippets, be careful to select parts that are tightly focused on the points you’d like to make... if you’re showing “real” (production) code you could even consider stripping out lines that aren’t directly relevant. You might also consider just throwing together some minimal examples to show the ideas you’re interested in (e.g., class Foo with method bar... but hopefully with some more descriptive/interesting names b/c those are overplayed XD )

**Comment by mmore500** [comment]
[Safari - Apr 23, 2020 at 00:09.pdf](https://github.com/mmore500/cse-491/files/4520228/Safari.-.Apr.23.2020.at.00.09.pdf)

**Comment by striebelhan** [comment]
Great blog post! It's well organized, clear, and concise.

**Comment by little11** [comment]
I've never quite understood data-oriented design, and your post was a really nice intro to it. The example case you chose is very illustrative and makes a lot of sense. My only suggestion is for the ordering of the post. You don't really define what data-oriented design actually is until toward the end in the "Can DOD and OOP coexist?" section. The "Introduction to Data-Oriented Design" section just explains what can go wrong with OOP. So inserting a sentence somewhere in there that defines DOD could make things a little clearer.

**Pull request merged**
