### PR TITLE
bradleys blog post

### PR DESCRIPTION
**Pull request by bradleybauer**
I would like to learn about c++20 ranges and views. I plan to document use cases of ranges while coding a neural network. Things I might comment on are performance, ease of implementation, and readability.

### CODE REVIEW

**Comment by mmore500** [comment]
excited to see more with ranges, they're very slick!

As you work, I would also keep an eye out for points RE: composability (being able to flexibly and intuitively re-arrange elements of the neural net) and maintainability.

If you're looking for a dataset to try your neural net out on, [MNIST](https://en.wikipedia.org/wiki/MNIST_database) is a classic choice & you can get [decent results](http://yann.lecun.com/exdb/mnist/) with a relatively small/simple network.

**Comment by mmore500** [comment]
Just read through the outline, looks like there will be some heavy duty code really taking ranges for a spin! As you're working, I'd recommend keeping the code in a separate github repo with a Makefile etc. so that readers can grab a copy to run and play around with without having to copy/paste the individual components out of the blog post itself. (If it's compact enough you could even throw a secondary copy onto CompilerExplorer/godbolt.) This will also free you from having to put each and every line of the code into the blog post. That way, you can be more selective about what you'd like to highlight in the blog post. Each of the sections you outlined would be neat functionality worth showing off on their own blog post, so I'd recommend working each up one to compile and run then writing its corresponding blog section and then moving on to the next section. That way, you can easily scale the blog post based on how tricky/time-consuming the different sections turn out to be.

**Comment by mmore500** [comment]
[Safari - Apr 22, 2020 at 23:24.pdf](https://github.com/mmore500/cse-491/files/4520146/Safari.-.Apr.22.2020.at.23.24.pdf)

**Comment by striebelhan** [comment]
Great blog post! Your examples showed some pretty cool things you can do with ranges. I'm not very familiar with ranges, so I learned a lot! I think for the same reason, I got a little tripped up with some of the syntax at the beginning. It might help to have a short section before your first example explaining what your code does in words to give a little extra context.

**Comment by little11** [comment]
Overall it's an interesting post and you've got nice code examples. My biggest comment is that since you include the namespaces for ranges and views, it was sometimes hard to recognize which functions came from those libraries in your examples. That's for someone like me who isn't particularly familiar with range functions though; if your intended audience already knows the topic well then it's fine as is. I'd also suggest shortening/splitting that one really long line comment in your last block of code so it all shows without scrolling (I had the same problem with my code examples).

**Comment by kennedysean** [comment]
Great post with a lot of good examples. For someone like me who is not very familiar with views, I think it would be super helpful to specify the namespace with each identifier rather than pulling in the entire ranges::views namespace, even if you just changed it in the code snippets rather than in the actual repository.

**Pull request merged**
